### ISSUE TITLE
Draft class diagrams for database structure.

### ISSUE THREAD

**Issue by t3sunu00Nuwan** [movieapp-group7/movieApp#4]

**Comment by PruttinuShane** [comment]
https://lucid.app/lucidchart/4373d7aa-85c6-4542-bf5b-91ea3c24346d/edit?viewport_loc=-2062%2C-418%2C4526%2C2300%2C0_0&invitationId=inv_8fd9e1ee-4ace-49e7-b435-e0f07d4778a2

**Comment by PruttinuShane** [comment]
Updated the name and Id for the account table
